### PR TITLE
Kannada translation

### LINKED ISSUE #9: Make Kannada locale
Use the English (`en.json`) translations from the i18n folder in assets with the exception of the shell folder. Each file name should be named `kn.json`
https://github.com/tedaky/memory-game/tree/master/projects/the-application/src/assets/i18n

### PR DESCRIPTION
**Pull request by sandarshsridhar**
Added Kannada (IT IS NOT PRONOUNCED AS CANADA) translation files

Closes #9

### CODE REVIEW

**Comment by tedaky** [comment]
Are these files supposed to be named as `ka`? I did a locale look up for Kannada and I see `kn` https://en.wikipedia.org/wiki/Kannada

**Comment by sandarshsridhar** [comment]
I see. I wasn't aware of this. I'll rename the files.

**Comment by tedaky** [comment]
I renamed for you since it was easy to do

**Review by tedaky — APPROVED** [review]
I approve

**Pull request merged**
